SELECT ID AS PROJECT_ID,
    EXTRACT(YEAR FROM AGE(FINISH_DATE, START_DATE)) * 12
       + EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) AS MONTHS_COUNT
FROM project
WHERE AGE(FINISH_DATE, START_DATE) = (
    SELECT MAX(AGE(FINISH_DATE, START_DATE)) AS MONTHS_COUNT
    FROM project
);
