CREATE TYPE mood AS ENUM ('Trainee', 'Junior', 'Middle', 'Senior');
CREATE TABLE worker (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000),
	BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL mood NOT NULL,
    SALARY INTEGER CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000)
)

CREATE TABLE project (
    ID INTEGER PRIMARY KEY,
    CLIENT_ID INTEGER NOT NULL,
    START_DATE DATE,
    FINISH_DATE DATE,
    CONSTRAINT FK_Client_ID FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
);

CREATE TABLE project_worker (
	PROJECT_ID INTEGER REFERENCES project(ID),
	WORKER_ID INTEGER REFERENCES worker(ID),
	PRIMARY KEY (PROJECT_ID, WORKER_ID)
);